version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  
  # ---- ADD THIS SECTION ----
  # This runs commands after the main build process
  jobs:
    post_build:
      # This command cleans the PDF output directory, leaving only the .pdf file
      - find "$READTHEDOCS_OUTPUT/pdf/" -type f ! -name "*.pdf" -delete
  # -------------------------

# Build documentation in the "docs/" directory with Sphinx
sphinx:
    configuration: source/conf.py

# Explicitly tell Read the Docs to build a PDF
#formats:
 # - pdf

# Install your project's dependencies
python:
    install:
    - requirements: requirements.txt